# Generated by Django 6.0.2 on 2026-09-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled',
            new_name='enrolled_at',
        ),
    ]
